//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicShowArchives.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performed_Show
    {
        public int Id { get; set; }
        public Nullable<int> ShowId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string Date { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual MagicShow MagicShow { get; set; }
    }
}
